- README.md
- static/js/webrtc.js
Looks like there's no test suite on this one?
> Instructions and correct error message for localhost

- static/js/webrtc.js
When you clicked the "Enable Audio/Video Chat" checkbox, it has been calling `localStream.stop()`. However this function was deprecated in 2015 and is disabled on my current browser. This change calls `.stop()` separately on the video and audio track.
It also falls back to the old style behavior in case the user has an old browser. Alternately we could skip that if we're not supporting such old browsers.
> Update stream stopping to account for disabled MediaStream.stop() function

- static/js/getUserMediaPolyfill.js
- static/js/webrtc.js
* Handle existing errors more accurately, including:
* Account for what seems like a _change_ in WebRTC error behavior
* Fixing #31 (proper error message for user not giving permission)
* Handle a few more errors
---
So here's a couple very fun facts:
* In some browsers (I suspect slightly old ones), `NotAllowedError` would mean _either_ that the user disallowed access to the camera/mic, _or_ the connection was insecure. As such, the only way I can think of distinguishing them is by checking for `https` (as we sortof were before I "fixed" it in a previous PR)
* In other browsers (I suspect the most recent), `NotAllowedError` thankfully only means that the user disallowed access to the camera/mic. However, insecure connections are instead handled by hiding `navigator.mediaDevices`, …
> Error messages

- static/js/webrtc.js
@JohnMcLear per our conversation in #23 it sounded like you wanted users to be able to override `settings.json` with cookies or URL vars. However currently, this is not _entirely_ the case for the existing setting (`ep_webrtc.enabled`).
The override fails if:
* `ep_webrtc.enabled` is set to `false` and the cookie is set to `true`.
The override does succeed if:
* `ep_webrtc.enabled` is set to `true` and the cookie is set to `false`.
* The user uses the URL var (both `false` to `true` and `true` to `false`)
It looks as though this may have been deliberate. I'm not sure what the idea was, though. Here's the relevant change and PR: 886ab4f8 #9 
My change here lets the user override with the cookies, and of course continues to allow them to override with URL vars. However, if you really meant …
> Let user cookies override settings for "Enable Audio/Video Chat"

- README.md
- index.js
- static/js/webrtc.js
Initial suggestion was making the stats stats POST endpoint. The specific there didn't seem that important, and websockets seemed to be a bit more in line with how things work, so I went with that, but @JohnMcLear np if you specifically wanted POST here.
> Error stats

- locales/en.json
- static/js/webrtc.js
Toward the goal (#31) of customizing error messages and all i18n strings, we start here by making error messages into i18n strings.
The i18n string override feature should go into etherpad-lite itself I think.
> i18n webrtc errors

- locales/en.json
1. Updated pad.ep_webrtc.error.otherCantAccess to be more explicit and to imply that the issue isn't because of an Etherpad problem.
2. Fixed a capitalization error in pad.ep_webrtc.error.other.
3. Updated pad.ep_webrtc.error.notSupported.howTo to include a full list of common browsers that are confirmed working with ep_webrtc.
> Update en.json Error Language

- static/tests/frontend/specs/checkbox.js
- static/tests/frontend/specs/enable_disable.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/interface_buttons.js
Many cookie problems were already addressed by ether/etherpad-lite#4905, as of this writing still in PR. After that PR and this one, the tests work again on Firefox and Chrome, for me anyway.
Fixed here:
Some regressions from switching to async/await; `helper.chrome$` was not ready.
One issue with css size imprecision.
One issue with how for some reason cookies don't have `{:}` characters espaped, while they do have others escaped.
> Fix tests again

- index.js
* Fix fetching of socket.io Sockets for a pad
* Check for sessioninfo when handling RTC message
This fixes two distinct null dereference bugs caused by users disconnecting between an event is triggered and when the event is handled.
@packardone These are the changes I applied yesterday. The second supersedes @JohnMcLear's monkey patch.
> Fix crashes caused by asynchronous events

- package.json
- static/js/webrtc.js
As of Etherpad 1.8.7, `$.gritter()` no longer accepts HTML in error messages. Convert the strings to jQuery objects as needed.
Also:
* Ensure that `clientVars.webrtc` is non-null.
* Fix wrapping of a long error message.
> Improve error messages

- static/js/adapter.js
This should fix "TypeError: Attempted to assign to readonly property" errors with Safari.
Downloaded from: https://webrtchacks.github.io/adapter/adapter-latest.js
FYI @packardone. I'll rebase the new ep_screenrtc stuff on top of this once this is merged.
> Update adapter.js to latest upstream version

- static/js/webrtc.js
The intermediate `RTCIceCandidate` object is unnecessary and seems to cause the following error on Chrome 68 (released ~2.5 years ago) when the end-of-candidates signal arrives:
Error: Failed to construct 'RTCIceCandidate': The 'candidate'
property is not a string, or is empty.
at new RTCIceCandidate
at Object.receiveMessage
at Object.handleClientMessage_RTC_MESSAGE [as hook_fn]
at callHookFnSync
at hooks.map
at Array.map
at Object.exports.callAll
at Object.handleMessageFromServer
at r.socket.on
at r.emit
cc @packardone
> Pass `RTCIceCandidateInit` object directly to `addIceCandidate()`

- static/js/webrtc.js
This fixes a bug affecting versions v0.1.11 to v0.1.26 (inclusive) introduced in commit 62b1ce8e28bef49bd6b31cbd6405bd0385719a26.
> Fix handling of `notify` arg to `hangup()`

- locales/en.json
- static/js/webrtc.js
- static/tests/frontend/specs/errors.js
* Reword error messages
* Don't hide the WebRTC box on error
* Let Etherpad's error handling handle unknown errors
* Don't swallow RTCPeerConnection errors
* Merge `getUserMedia()` into `activate()`
* Only call `showUserMediaError()` for `getUserMedia()` errors
* Leave deactivated if `getUserMedia()` fails
* tests: Redo `errors.js` tests
cc @packardone
> Improve error handling

- static/js/webrtc.js
FYI @packardone: The bug this PR fixes does not exist in your production version due to the way https://github.com/26llc/ep_webrtc/commit/5e8dcf4e14eeaa75fb16fa410ce4c40fa5a80bff was written.
> Always enable when URL has `av=YES`, even if disabled by cookie

- ep.json
- static/js/webrtc.js
* Avoid unnecessary calls to `getUserFromId()`
* Convert color ID to color
* Gracefully handle missing peer name or color
* Factor out duplicate code to set peer name and color
* Use `userJoinOrUpdate` instead of `aceSetAuthorStyle`
Fixing name/color updates is not urgent, but it makes it easier to fix the tests.
cc @packardone
> Fix handling of peer name/color updates

- static/js/webrtc.js
* Don't call `getUserMedia()` if both audio and video disabled
* Avoid flicker if the stream hasn't changed
The former is a prereq to fixing tests.
cc @packardone
> Minor fixes

- README.md
- index.js
- static/js/webrtc.js
- static/tests/frontend/specs/enable_disable.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/interface_buttons.js
- static/tests/frontend/specs/setStream.js
- templates/settings.ejs
* Improve readability of settings processing
* Use empty string instead of `unchecked` for checkbox
* Always register `unload` handler
* Also call `hangupAll()` during `beforeunload` event
* Merge `setupCheckboxes()` into `init()`
* Use `URLSearchParams` to parse the query string
* Use `settingToCheckbox()` for `av` query parameter
* Add support for `av=NO`
* Coerce to boolean rather than compare with `true`
* Mute/unmute all tracks
* Improve readability of `<video>` element creation
* Check all tracks when checking audio/video enabled state
* Improve readability of `addInterface()`
* Move `<video>` element creation to `addInterface()`
* Use `hangupAll()` to clean up old connections when activating
cc @packardone
> Various minor cleanups and fixes

- index.js
- static/js/webrtc.js
- static/tests/frontend/specs/setStream.js
* Always assume remote streams could have audio
* Sync interface buttons for self view with stream state
* Factor out duplicate video element ID code
* Always put the self view first
* Unconditionally clear the self view
* Add support for message broadcasts
* Simplify RTC_MESSAGE format a bit
* Factor out duplicate `addTrack()` calls
* Close RTCPeerConnection before overwriting it
* Use destructuring to improve readability
* Inline `call()`
* Inline `init()` into `postAceInit()`
* Consistently use `this.getUserId()`
* Use `negotiationneeded` to trigger offer
* Always create peer connection when receiving a message
* Combine offer/answer into a single description handler
* Send an invite to connect rather than directly connect
* Invite newly discovered peers
* Always …
> Numerous fixes and improvements

- static/js/webrtc.js
- static/tests/frontend/specs/audio_video_on_start.js
- static/tests/frontend/specs/checkbox.js
- static/tests/frontend/specs/enable_disable.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/interface_buttons.js
- static/tests/frontend/specs/race_conditions.js
- static/tests/frontend/specs/setStream.js
- static/tests/frontend/utils.js
* tests: Remove undocumented `fake` constraint
* tests: Factor out common `cartesian()` function
* tests: Remove unnecessary `makeVideoTrack()` parameters
* tests: Make the fake stream function match the behavior of `getUserMedia()`
* tests: Increase initialization timeout
* tests: Wait for activation to complete to avoid race conditions
* tests: Delete overly strict `race_conditions.js` timeouts
* tests: Move `fakeGetUserMedia` to `utils.js` for reuse
* tests: Add video constraint support to `fakeGetUserMedia()`
* tests: Animate the dummy video track
* tests: Avoid calling `getUserMedia()` where feasible
cc @packardone
> tests: Fake webcam improvements

- static/css/webrtc.css
- static/js/webrtc.js
- static/tests/frontend/specs/interface_buttons.js
* Set video element box-sizing to content-box
* Delete unused `.error-msg` style
* Move colored border to `.video-container`
* Remove nearly imperceptible border radius
* Set a minimum height for `.video-container`
* Draw a small black border around the video
* Delete syntactically invalid `@media` at-rule
* Prevent `.video-container` from shrinking below video size
* Rely on CSS to put the self-view first
* Tweak `#rtcbox` flex growth/shrink
* Delete redundant `justify-content` rule
* Automatically size the video element
* Make videos user-resizable
Fixes #58
cc @packardone
> Make videos resizable and other CSS improvements

- static/js/webrtc.js
This fixes the following error on iOS (Chrome and Safari):
> NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
This partially reverts commit 05b929217cc167a88bd28d97fd360a67b089eb4d.
cc @packardone
> Add back `playsinline` and `autoplay` on video element

- locales/en.json
- static/js/index.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/race_conditions.js
* Fix indentation
* Add more debug messages
* Delete unused `_tracks` variable
* Join concurrent `activate()`/`deactivate()` calls
* Treat OverconstrainedError like NotFoundError
* Prevent recursion during auto-unmute
* Silence `peerIdentity` rejections
* Fix handling of changed peer session and instance IDs
* Call `unmuteAutoMuted()` at the end of the click handler
cc @packardone
> Various fixes

- static/js/index.js
- static/tests/frontend/specs/interface_buttons.js
- static/tests/frontend/specs/race_conditions.js
- static/tests/frontend/utils.js
* Make all local track modifications in `updateLocalTracks()`
* Keep track of when the click handlers are busy
* tests: Redo `race_conditions.js` tests
* tests: Use the pad's `setInterval` for the animation loop
* tests: Increase frame rate to speed up tests
* tests: Actually generate silence from `makeSilentAudioTrack()`
* tests: Fix `interface_buttons.js` race on Safari
cc @packardone
> test improvements (and prerequisite refactoring)

- static/js/index.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/interface_buttons.js
* Defer `getMedia()` call until the user enables the camera/microphone
* Warm up RTC connections with a dummy track
* Ignore ended local media tracks
* Factor out self-view button DOM manipulations
* Stop streaming local tracks that have ended
* Update the self-view UI if the browser ends a local track
* Also try playing videos when auto-unmuting
* Add a sanity check to prevent infinite recursion when auto-muting
* Ignore `HTMLVideoElement.play()` errors
cc @packardone
> More UX improvements

- static/js/index.js
Before this change the errors weren't actually logged. That's what I get for hastily tossing together something without thorough testing.
cc @packardone
> Fix logging of `play()` and `getUserMedia()` errors

- static/js/adapter.js
- static/js/index.js
* Compat: Update adapter.js to v8.0.0
* Compat: `EventTarget` constructor polyfill
* Compat: Nullary `RTCPeerConnection.setLocalDescription()`
* Compat: Don't close when there is an ICE closed event
* Compat: Reset the connection on connection closed event
* Compat: Check for `restartIce()` before calling it
* Compat: Reset connection if SLD fails
cc @packardone
> Old browser compatibility fixes

- static/js/index.js
This should improve UX if the track ended due to a temporary condition.
cc @packardone
> Retry when clicking "local audio/video stopped unexpectedly" alert

- static/js/index.js
* Check if PC is closed when local track changes
* Convert an exception into a debug message
* Defer logging disconnect until after `userLeave` hook fires
* Defer logging errors in case they are caused by navigating away
cc @packardone
> Reduce error log spam

- static/js/index.js
There's no good reason to fail if the browser is unable to get a camera stream smaller than 320x240. Some browsers might have a hard time getting a stream smaller than 320x240 if the camera is in portrait mode.
cc @packardone
> Switch video constraints from `max` to `ideal`

- static/js/index.js
It's already muted, but maybe this will work around Safari's echo bug. (This is a long shot.)
cc @packardone
> Set self-view volume to 0
