ether/ep_webrtc

- static/js/webrtc.js
If it's muted, the option should be to unmute, etc.
> Fix Un/Muted title

- README.md
- index.js
- static/css/webrtc.css
- static/js/webrtc.js
Allow `video.size.small` and `video.size.large` in `settings.json` to dictate how big the video windows are when normal and maximiized, respectively.
See #52
> Custom video size

- index.js
Affected cases where video.settings is not defined in settings.json
> Undefined variable bug

- .travis.yml
- README.md
- static/js/webrtc.js
- static/tests/frontend/specs/enable_disable.js
Requires https://github.com/ether/etherpad-lite/pull/4042
> Test for enable-disable

- .travis.yml
- static/tests/frontend/specs/enable_disable.js
Not sure why I didn't clear cookies in that one test. Maybe this will fix it on saucelabs?
> Undo Travis testing stuff and fix a test

- locales/en.json
- locales/fr.json
> Add French translation

- index.js
- package-lock.json
- package.json
- static/js/adapter.js
- static/js/webrtc.js
- static/tests/frontend/specs/enable_disable.js
- static/tests/frontend/specs/errors.js
- static/tests/frontend/specs/interface_buttons.js
* lint: Revert lint fixes to `adapter.js`
* lint: Update ESLint dependencies
* lint: Run `eslint --fix`
* lint: Fix some camelcase warnings
> lint fixes

- index.js
- static/js/webrtc.js
- static/tests/frontend/specs/checkbox.js
* Factor out duplicate logic
* Use `async` and `await` for readability
* Use null instead of empty string when removing stream
* Use `.includes(thing)` instead of `.indexOf(thing) > -1`
* Simplify `avInURL()`
* Modernize hook functions
* Invert conditions to improve readability
> Various minor cleanups

- README.md
- index.js
- static/js/webrtc.js
> Use non-deprecated WebRTC API

- static/js/webrtc.js
Minor cleanup PR that will make it easier to update tests.
cc @packardone
> `await` the results of `async` functions

- ep.json
- static/js/webrtc.js
To improve readability/maintainability.
cc @packardone
> Use ES6 class syntax

- static/css/webrtc.css
cc @packardone. This is deployed on the test server.
> Fix video resizing on Safari

- static/js/index.js
* Connect to peers while awaiting camera/microphone access
* Hide peer UI on RTC disconnect event
cc @packardone
> UX improvements

- static/css/styles.css
- static/js/index.js
* CSS: Scope all rules to `#rtcbox`
* CSS: Multiple improvements to the interface buttons and name
* CSS: Disable size change transition during drag resizing
* CSS: Remove 5px gap to the left of the name box
* CSS: Delete unused max-width, max-height transition rules
* CSS: Tweak formatting of user name display
cc @packardone
> Multiple CSS improvements

- ep.json
- index.js
- static/js/index.js
- templates/editorContainerBox.ejs
* Find video container by ID, not parent of video
* Move rtcbox creation to client-side initialization
cc @packardone
> Code health cleanups

- static/js/index.js
* Set the name display element's title to the full name
* Hide the enlarge button unless there is video
cc @packardone
> More UX improvements

- static/js/index.js
> Log `play()` and `getUserMedia()` errors to the server

- static/js/index.js
> Log connection lost and local track stopped events to server

- static/js/index.js
> Try unmuting auto-muted videos after getting access to the camera/mic

- README.md
- index.js
- static/js/index.js
Untested. I will test it once the test coturn server is set up.
cc @packardone
> Add support for coturn's ephemeral passwords

- static/js/index.js
> Re-invite the peer on disconnect

- static/js/index.js
> Log more errors to the server

- static/js/index.js
This fixes a "TypeError: this.logErrorToServer is not a function" error inside `PeerState` (introduced in commit 003b89859a61c4a2a71f0931cba37e56a0e4ee5e) when renegotiation is required.
cc @packardone
> Move `logErrorToServer()` out of the `ep_webrtc` object

- static/js/index.js
> Log all connection resets caused by an error

- README.md
- locales/en.json
- static/css/styles.css
- static/js/index.js
> Add screen sharing feature

- static/js/index.js
> Log the peer message if it causes an error

- README.md
- index.js
- static/js/index.js
Also make the video resolution configurable.
cc @packardone
> Decrease default video resolution

- README.md
- ep.json
- index.js
- package-lock.json
- package.json
> Add support for Xirsys ephemeral credentials

- static/js/adapter.js
Downloaded from: https://webrtchacks.github.io/adapter/adapter-latest.js
> Update adapter.js to v8.1.1

- static/js/index.js
Perfect negotiation isn't needed because we can trivially select one peer as the caller and the other as the answerer. Some browsers seem to have problems with perfect negotiation (Safari in particular); hopefully this will reduce the number of errors seen in the wild.
(This is another long shot attempt to fix the echo bug.)
cc @packardone
> Simplify peer negotiation

- static/js/index.js
@packardone I'm hoping this works around the Safari echo bug.
> Use empty transceivers to warm up connection

- README.md
- index.js
- package-lock.json
- package.json
- static/tests/backend/init.js
- static/tests/backend/specs/sharding.js
> Add basic sharding support
